# -*- coding: utf-8 -*-
"""GA8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-3jtk4n6gr9pxN9xwn6Vq4T7wvdobSvu
"""

import streamlit as st

def find_largest_number(a, b, c):
    return max(a, b, c)

def main():
    st.title("21f1003409_GA_8")
    st.title("Find the Largest Number")

    st.write("Enter three numbers:")
    a = st.number_input("Enter the first number:")
    b = st.number_input("Enter the second number:")
    c = st.number_input("Enter the third number:")

    if st.button("Find Largest"):
        if a >= b and a >= c:
            largest = a
        elif b >= a and b >= c:
            largest = b
        else:
            largest = c

        st.write(f"The largest number among {a}, {b}, and {c} is: {largest}")

if __name__ == "__main__":
    main()
